@SmartMedCC_AndreSousa_HostAddress = http://localhost:5253

# CREATE
POST {{SmartMedCC_AndreSousa_HostAddress}}/medications/
Content-Type: application/json
Accept: application/json

{
    "name": "Ben-u-ron",
    "quantity": 4
}

# GET ALL
GET {{SmartMedCC_AndreSousa_HostAddress}}/medications/
Accept: application/json

# GET BY ID
GET {{SmartMedCC_AndreSousa_HostAddress}}/medications/1
Accept: application/json

# UPDATE
PUT {{SmartMedCC_AndreSousa_HostAddress}}/medications/
Content-Type: application/json
Accept: application/json

{
    "id": 1,
    "name": "Ben-u-ron 2",
    "quantity": 2
}

# DELETE
DELETE {{SmartMedCC_AndreSousa_HostAddress}}/medications/1
Accept: application/json
